In [1]:
import pandas as pd

In [2]:
# read the file

nba_df = pd.read_csv("nba_games.csv")

nba_df

,Unnamed: 0,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,0,240,240,39,81,0.481,6,20,0.300,14,...,22.8,29.0,178,111,DAL,95,1,2016,12/9/2015,True
1,1,240,240,36,100,0.360,7,31,0.226,16,...,50.0,32.6,152,111,ATL,98,0,2016,12/9/2015,False
2,2,240,240,37,85,0.435,8,19,0.421,17,...,20.0,30.9,148,116,SAS,107,1,2018,10/18/2017,False
3,3,240,240,41,89,0.461,8,21,0.381,17,...,28.6,30.9,138,118,MIN,99,0,2018,10/18/2017,True
4,4,240,240,27,86,0.314,6,26,0.231,15,...,16.8,30.9,157,90,MEM,92,1,2021,4/30/2021,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,17767,240,240,35,81,0.432,11,26,0.423,27,...,34.2,33.7,160,118,OKC,92,0,2019,10/19/2018,True
17768,17768,240,240,37,74,0.500,13,25,0.520,26,...,25.0,30.0,139,129,ORL,108,1,2017,12/14/2016,True
17769,17769,240,240,42,89,0.472,14,33,0.424,10,...,25.6,29.9,175,126,LAC,113,0,2017,12/14/2016,False
17770,17770,240,240,41,85,0.482,9,26,0.346,26,...,27.7,27.1,150,126,MIA,106,1,2020,9/19/2020,True
17771,17771,240,240,33,85,0.388,12,44,0.273,28,...,51.5,36.2,141,114,BOS,117,0,2020,9/19/2020,False

### Data Cleaning and Data Preparing

In [3]:
nba_df = nba_df.sort_values("date")
nba_df = nba_df.reset_index(drop=True)

In [4]:
del nba_df["mp.1"]
del nba_df["mp_opp.1"]
del nba_df["index_opp"]
del nba_df["Unnamed: 0"]

In [7]:
def add_target(group):
    group["target"] = group["won"].shift(-1)
    return group

nba_df = nba_df.groupby("team", group_keys=False).apply(add_target)

In [8]:
# lets take a look at some stats 
# washington nba_df[nba_df["team"] == "WAS"]

# dallas mavs 
nba_df[nba_df["team"] == 'DAL']

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
5,240,32,88,0.364,7,31,0.226,11,14,0.786,...,33.0,206,102,MIA,106,1,2016,1/1/2016,False,True
49,240,32,78,0.410,12,37,0.324,17,23,0.739,...,29.7,144,103,MIA,83,0,2021,1/1/2021,True,True
80,240,36,77,0.468,6,20,0.300,15,21,0.714,...,39.4,282,116,MIN,87,1,2016,1/10/2016,True,True
119,240,39,83,0.470,15,36,0.417,22,28,0.786,...,37.8,158,121,CHO,111,1,2018,1/10/2018,True,False
161,240,39,96,0.406,11,38,0.289,25,37,0.676,...,43.1,221,126,LAL,129,0,2020,1/10/2020,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17597,240,38,85,0.447,12,37,0.324,23,33,0.697,...,39.0,284,113,LAC,154,1,2020,8/25/2020,False,False
17618,240,38,90,0.422,11,37,0.297,10,17,0.588,...,64.0,170,105,LAC,111,0,2020,8/30/2020,False,True
17629,265,33,90,0.367,9,41,0.220,39,50,0.780,...,37.8,183,114,SAC,110,1,2020,8/4/2020,True,False
17659,240,39,87,0.448,17,48,0.354,16,21,0.762,...,32.7,245,126,LAC,126,0,2020,8/6/2020,False,True
17681,265,48,115,0.417,17,53,0.321,23,25,0.920,...,45.1,157,125,MIL,132,0,2020,8/8/2020,True,NaN

In [14]:
# see null values 
nba_df["target"][pd.isnull(nba_df["target"])] = 2
nba_df["target"] = nba_df["target"].astype(int, errors="ignore")

C:\Users\Adib1\AppData\Local\Temp\ipykernel_29320\3242683284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba_df["target"][pd.isnull(nba_df["target"])] = 2

In [15]:
# see won there will always be a winner and loser 
nba_df["won"].value_counts()

True     8886
False    8886
Name: won, dtype: int64

In [16]:
# see the target as well to determine 
nba_df["target"].value_counts()
# 1 win ; 0 = loss 2 = doesnt have next game

1    8873
0    8869
2      30
Name: target, dtype: int64

In [18]:
nulls = pd.isnull(nba_df).sum()
nulls = nulls[nulls > 0]
valid_columns = nba_df.columns[~nba_df.columns.isin(nulls.index)]
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [19]:
# dont want copy warning 
nba_df = nba_df[valid_columns].copy()
nba_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240,36,91,0.396,15,33,0.455,17,18,0.944,...,30.6,174,130,CHO,94,0,2016,1/1/2016,True,1
1,240,33,87,0.379,5,16,0.313,22,29,0.759,...,40.4,150,105,PHI,84,0,2016,1/1/2016,True,0
2,240,39,85,0.459,10,16,0.625,20,25,0.800,...,39.6,171,132,NYK,81,0,2016,1/1/2016,True,0
3,240,31,84,0.369,6,19,0.316,13,17,0.765,...,42.7,195,102,CHI,108,1,2016,1/1/2016,False,0
4,240,31,84,0.369,4,24,0.167,18,25,0.720,...,30.6,164,100,LAL,93,1,2016,1/1/2016,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240,38,81,0.469,12,30,0.400,14,14,1.000,...,37.2,151,123,LAL,112,0,2020,9/8/2020,False,2
17768,240,27,68,0.397,9,27,0.333,22,26,0.846,...,34.3,143,106,LAC,96,0,2020,9/9/2020,False,2
17769,240,33,79,0.418,8,28,0.286,22,30,0.733,...,35.5,162,117,DEN,85,1,2020,9/9/2020,True,2
17770,290,44,101,0.436,19,47,0.404,18,25,0.720,...,32.5,300,120,BOS,122,1,2020,9/9/2020,True,2
17771,290,44,100,0.440,19,46,0.413,15,18,0.833,...,23.7,149,117,TOR,125,0,2020,9/9/2020,False,2

### Best Feature model for Machine Learning

In [20]:
from sklearn.linear_model import RidgeClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, 
                                n_features_to_select=30, 
                                direction="forward",
                                cv=split,
                                n_jobs=1
                               )

In [21]:
# we cant scale these 
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]
selected_columns = nba_df.columns[~nba_df.columns.isin(removed_columns)]

In [22]:
# Min and Max Scale to determine 
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
nba_df[selected_columns] = scaler.fit_transform(nba_df[selected_columns])

In [23]:
nba_df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.386364,0.455882,0.303828,0.517241,0.439394,0.540380,0.372093,0.269841,0.934656,...,0.109114,0.402844,0.623529,CHO,0.288462,0.0,2016,1/1/2016,True,1
1,0.0,0.318182,0.397059,0.263158,0.172414,0.181818,0.371734,0.488372,0.444444,0.718786,...,0.234917,0.289100,0.329412,PHI,0.192308,0.0,2016,1/1/2016,True,0
2,0.0,0.454545,0.367647,0.454545,0.344828,0.181818,0.742280,0.441860,0.380952,0.766628,...,0.224647,0.388626,0.647059,NYK,0.163462,0.0,2016,1/1/2016,True,0
3,0.0,0.272727,0.352941,0.239234,0.206897,0.227273,0.375297,0.279070,0.253968,0.725788,...,0.264442,0.502370,0.294118,CHI,0.423077,1.0,2016,1/1/2016,False,0
4,0.0,0.272727,0.352941,0.239234,0.137931,0.303030,0.198337,0.395349,0.380952,0.673279,...,0.109114,0.355450,0.270588,LAL,0.278846,1.0,2016,1/1/2016,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.431818,0.308824,0.478469,0.413793,0.393939,0.475059,0.302326,0.206349,1.000000,...,0.193838,0.293839,0.541176,LAL,0.461538,0.0,2020,9/8/2020,False,2
17768,0.0,0.181818,0.117647,0.306220,0.310345,0.348485,0.395487,0.488372,0.396825,0.820303,...,0.156611,0.255924,0.341176,LAC,0.307692,0.0,2020,9/9/2020,False,2
17769,0.0,0.318182,0.279412,0.356459,0.275862,0.363636,0.339667,0.488372,0.460317,0.688448,...,0.172015,0.345972,0.470588,DEN,0.201923,1.0,2020,9/9/2020,True,2
17770,0.5,0.568182,0.602941,0.399522,0.655172,0.651515,0.479810,0.395349,0.380952,0.673279,...,0.133504,1.000000,0.505882,BOS,0.557692,1.0,2020,9/9/2020,True,2
17771,0.5,0.568182,0.588235,0.409091,0.655172,0.636364,0.490499,0.325581,0.269841,0.805134,...,0.020539,0.284360,0.470588,TOR,0.586538,0.0,2020,9/9/2020,False,2